# This file defines states and attache behaviors and priorities for helm


helm_configuration:
  frequency: 10.0

finite_state_machine:
  - name: start
    mode: idle
    initial: true
    transitions:
      - float
      - depth_hold
      - move_auv
      - kill

  - name: float
    mode: hold_depth_float
    transitions:
      - start
      - kill

  - name: depth_hold
    mode: hold_depth_auv
    transitions:
      - start
      - move_auv
      - kill
  
  - name: move_auv
    mode: crusing_auv
    transitions:
      - start
      - depth_hold
      - kill

  - name: kill
    mode: idle
    transition:
      - start


behaviors:
  - name: floating
    plugin: helm::DirectControl
    states:
      - { name: float, priority: 1 }
  
  - name: depth_holding
    plugin: helm::DirectControl
    states:
      - { name: depth_hold, priority: 1 }
  
  - name: moving
    plugin: helm::DirectControl
    states:
      - { name: move_auv, priority: 1 }
