# This file defines states and attache behaviors and priorities for helm


helm_configuration:
  frequency: 10.0

finite_state_machine:
  - name: start
    mode: idle
    initial: true
    transitions:
      - float
      - survey_global
      - kill

  - name: float
    mode: hold_depth
    transitions:
      - start
      - drift
      - kill

  - name: drift
    mode: move
    transitions:
      - start
      - float
      - kill

  - name: kill
    mode: idle
    transition:
      - start


behaviors:
  - name: floating
    plugin: helm::DirectControl
    states:
      - { name: float, priority: 1 }

  - name: drifting
    plugin: helm::DirectControl
    states:
      - { name: drift, priority: 1 }

  - name: depth_tracking
    plugin: helm::DepthTracking
    states:
      - { name: survey_local, priority: 1 }
      - { name: survey_global, priority: 1 }

  - name: periodic_surfacing
    plugin: helm::PeriodicSurface
    states:
      - {name: survey_local, priority: 2}
      - {name: survey_global, priority: 2}

  - name: gps_wpt
    plugin: helm::GpsWaypoint
    states:
      - {name: survey_global, priority: 1}